# ATTENTION: ALL CLOUDCANNON CMS CONFIGURATION NOW LIVES IN cloudcannon.config.yml

# ------------------------------------------------
# DEFINE GLOBAL VARIABLES
# ------------------------------------------------

# Site settings
client: TBD
title: Home Data Inspector Content
description: Serves up JSON files to be consumed by the Home Data Inspector App
email: dev@ocupop.com
url: ""
permalink: pretty

placeholder_image: https://via.placeholder.com/1000x1000/333333/000000?text=Placeholder


# ------------------------------------------------
# DEFINE COLLECTIONS
# (All CloudCannon CMS config is set in cloudcannon.config.yml)
# ------------------------------------------------
# collections:
#   examples:
#     output: true
#     permalink: /examples/:path/


# ------------------------------------------------
# DEFINE DEFAULT VALUES
# (useful for setting layout for page types without having them editable by the user)
# ------------------------------------------------
# defaults:
#   -
#     scope:
#       type: 'page'
#     values:
#       layout: default
#   -
#     scope:
#       type: 'post'
#     values:
#       layout: default


# ------------------------------------------------
# BUILD SETTINGS AND PLUGINS
# ------------------------------------------------
safe: false
sass:
  # style: compressed
  # sass_dir: _scss
# plugins:
#   - jekyll-sitemap